server:
  port: 80

mybatis:
  mapper-locations: classpath:com.yuegou.dao/*.xml
  type-aliases-package: com.yuegou.entity
#配置mybatis

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd hh:mm:ss.SSS}){cyan} %clr([%thread] %-5level %logger{50}) - %msg%n'
  file:
    path: C:\Users\Undertale\Desktop\悦购网上商城\19-23李春铭毕业设计\
    name: yuegou.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
      total-size-cap: 100MB

#配置日志格式

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuegou
    username: root
    password: root
    #配置数据源和数据库
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
    #开启彩色日志打印，设置文件上传下载限制
  jackson:
    date-format: yyyy-MM-dd mm:hh:ss
    #配置默认时间转换
  devtools:
    restart:
      enabled: true
      additional-paths: resources/**,static/**,templates/**
      exclude: date/**
  thymeleaf:
    cache: false
  #配置热部署,关闭thymeleaf缓存


paginationconfig:
  page: 1
  size: 2
#配置默认页码和读取行数

utils:
  token:
    tokenKey: YueGou_JWT_Key
    tokenExpirationTime: 43200000
  projecttasks:
    loginEmptCleanTime: 0 0/10 * * * *
    #登录验证检测执行间隔时间,这里是每十分钟执行一次。 0 0/10 * * * *
    detectionUnBanTime: 0 5 0 * * *
    #封号处理每次处理时间,这里是每天凌晨12:05分执行。
    bannerCarousel: 0 0 0 * * *
  imagessavepath: C:\Users\Undertale\Desktop\悦购网上商城\19-23李春铭毕业设计\images\
#配置token，密钥和有效时间


